name: Run Python script for TeX Live compilation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Restore TeX Live cache
      - name: Cache TeX Live
        uses: actions/cache@v3
        with:
          path: /usr/share/texlive
          key: ${{ runner.os }}-texlive
          restore-keys: |
            ${{ runner.os }}-texlive

      # Step 3: Install TeX Live if not cached
      - name: Install TeX Live if not cached
        run: |
          if [ ! -d /usr/share/texlive ]; then
            sudo apt-get update
            sudo apt-get install -y texlive-full
          fi

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 5: Run Python script to compile TeX files
      - name: Run TeX compile script
        run: |
          python html_embedding.py